[project]
name = "yomigana-ebook"
version = "0.2.3"
description = "The fastest converter to add yomigana(readings) to Japanese epub eBooks! (Using Mecab and Unidic)"
authors = [{ name = "Yu Chen", email = "rabbit19981023@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "japanese",
    "lightnovel",
    "ebook",
    "epub",
    "furigana",
    "yomigana",
    "kanji",
    "mecab",
    "unidic",
    "nlp",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "fugashi>=1.2.1,<2",
    "unidic>=1.1.0,<2",
    "beautifulsoup4>=4.12.2,<5",
    "lxml>=4.9.2,<5",
]

[project.urls]
Homepage = "https://github.com/rabbit19981023/yomigana-ebook"
Repository = "https://github.com/rabbit19981023/yomigana-ebook"

[project.scripts]
yomigana_ebook = "yomigana_ebook.cli:main"

[dependency-groups]
dev = ["black>=23.3.0,<24"]
test = [
    "pytest>=7.3.1,<8",
    "pytest-watcher>=0.2.6,<0.3",
    "pytest-testmon>=2.0.6,<3",
]

[tool.uv]
default-groups = "all"

[build-system]
requires = ["uv_build>=0.10.5,<0.11.0"]
build-backend = "uv_build"
